# Generated by Django 5.2.8 on 2025-11-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('recruiter', 'Recruiter')], default='student', max_length=10),
        ),
    ]
